import "./globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
import Header from "@/components/Header/index";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const aspira = localFont({
  src: [
    {
      path: "./aspira-regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./aspira-bold.woff2",
      weight: "700",
      style: "bold",
    },
    // {
    //   path: "./fonts/Aspira-Regular.woff",
    //   weight: "400",
    //   style: "normal",
    // },
    // {
    //   path: "./fonts/Aspira-Regular.woff",
    //   weight: "700",
    //   style: "bold",
    // },
  ],
  variable: "--font-aspira",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${aspira.variable} font-sans`}>
        <Header></Header>
        {children}
      </body>
    </html>
  );
}
