//? File were we store the hreflangs of the main pages and import ir on each of those pages

export const hreflangs = {
  home: {
    "x-default": "https://web.didiglobal.com/",
    "es-CL": "https://web.didiglobal.com/cl/",
    "es-PE": "https://web.didiglobal.com/pe/",
    "es-AR": "https://web.didiglobal.com/ar/",
    "es-CO": "https://web.didiglobal.com/co/",
    "es-EC": "https://web.didiglobal.com/ec/",
    "es-CR": "https://web.didiglobal.com/cr/",
    "es-DO": "https://web.didiglobal.com/do/",
    "es-PA": "https://web.didiglobal.com/pa/",
    "es-MX": "https://web.didiglobal.com/mx/",
    "en-AU": "https://web.didiglobal.com/au/",
    "en-NZ": "https://web.didiglobal.com/nz/",
    "ar-EG": "https://web.didiglobal.com/eg/",
  },
  pax: {
    "es-CL": "https://web.didiglobal.com/cl/pasajero/",
    "es-PE": "https://web.didiglobal.com/pe/pasajero/",
    "es-AR": "https://web.didiglobal.com/ar/pasajero/",
    "es-CO": "https://web.didiglobal.com/co/pasajero/",
    "es-EC": "https://web.didiglobal.com/ec/pasajero/",
    "es-CR": "https://web.didiglobal.com/cr/pasajero/",
    "es-DO": "https://web.didiglobal.com/do/pasajero/",
    "es-PA": "https://web.didiglobal.com/pa/pasajero/",
    "es-MX": "https://web.didiglobal.com/mx/pasajero/",
    "en-AU": "https://web.didiglobal.com/au/rider/",
    "en-NZ": "https://web.didiglobal.com/nz/rider/",
    "ar-EG": "https://web.didiglobal.com/eg/rider/",
  },
  drv: {
    "es-CL": "https://web.didiglobal.com/cl/conductor/",
    "es-PE": "https://web.didiglobal.com/pe/conductor/",
    "es-AR": "https://web.didiglobal.com/ar/conductor/",
    "es-CO": "https://web.didiglobal.com/co/conductor/",
    "es-EC": "https://web.didiglobal.com/ec/conductor/",
    "es-CR": "https://web.didiglobal.com/cr/conductor/",
    "es-DO": "https://web.didiglobal.com/do/conductor/",
    "es-PA": "https://web.didiglobal.com/pa/conductor/",
    "es-MX": "https://web.didiglobal.com/mx/conductor/",
    "en-AU": "https://web.didiglobal.com/au/driver/",
    "en-NZ": "https://web.didiglobal.com/nz/driver/",
    "ar-EG": "https://web.didiglobal.com/eg/driver/",
  },
  helpCenter: {
    "es-CL": "https://web.didiglobal.com/cl/centro-de-ayuda/",
    "es-PE": "https://web.didiglobal.com/pe/centro-de-ayuda/",
    "es-AR": "https://web.didiglobal.com/ar/centro-de-ayuda/",
    "es-CO": "https://web.didiglobal.com/co/centro-de-ayuda/",
    "es-EC": "https://web.didiglobal.com/ec/centro-de-ayuda/",
    "es-CR": "https://web.didiglobal.com/cr/centro-de-ayuda/",
    "es-DO": "https://web.didiglobal.com/do/centro-de-ayuda/",
    "es-PA": "https://web.didiglobal.com/pa/centro-de-ayuda/",
    "es-MX": "https://web.didiglobal.com/mx/centro-de-ayuda/",
    "en-AU": "https://web.didiglobal.com/au/help-center/",
    "en-NZ": "https://web.didiglobal.com/nz/help-center/",
    "ar-EG": "https://web.didiglobal.com/eg/help-center/",
  },
  food: {
    "es-PE": "https://web.didiglobal.com/pe/food/",
    "es-CO": "https://web.didiglobal.com/co/food/",
    "es-CR": "https://web.didiglobal.com/cr/food/",
    "es-MX": "https://web.didiglobal.com/mx/food/",
  },
  foodDelivery: {
    "es-PE": "https://web.didiglobal.com/pe/food/repartidores/",
    "es-CO": "https://web.didiglobal.com/co/food/repartidores/",
    "es-CR": "https://web.didiglobal.com/cr/food/repartidores/",
    "es-MX": "https://web.didiglobal.com/mx/food/repartidores/",
  },
  foodBusiness: {
    "es-PE": "https://web.didiglobal.com/pe/food/restaurantes/",
    "es-CO": "https://web.didiglobal.com/co/food/restaurantes/",
    "es-CR": "https://web.didiglobal.com/cr/food/restaurantes/",
    "es-MX": "https://web.didiglobal.com/mx/food/restaurantes/",
  },
};
